security:
    encoders:
        App\Entity\User:
            algorithm: sha1
    providers:
        main:
            id: App\Repository\UserRepository
    firewalls:
        main:
            anonymous: ~
            remember_me:
                secret:   '%env(APP_SECRET)%'
                token_provider: App\Repository\UserRemembermeTokenRepository
            form_login:
                login_path: auth_login
                check_path: auth_login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: front_index
                target_path_parameter: '_target_path'
                use_referer: false
                always_use_default_target_path: true
            logout:
                path:   auth_logout
                invalidate_session: true
                target: auth_login
            guard:
                authenticators:
                    - App\Security\Authenticator\OauthConnectAuthenticator

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
