vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            uri_prefix: /images/product_images
            upload_destination: '%kernel.project_dir%/public/images/product_images'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
